# Curriculum Vitae Wing-kien Alex Sung

- **Address**: De Kriek 29, Vleuten  
- **E-mail**: wkasung@gmail.com  
- **Phone**: +31 6 52220022  
- **Date of Birth**: 24 September 2000  
- **Nationality**: Dutch  

## Education {-}

- **2020 – Present**  
  **HU University of Applied Sciences, Utrecht, the Netherlands**  
  *BSc Life Science*  
  - Biomolecular Research specialisation  
  - Minor: Data Science for Biology  
  - Honours Programme  
  - Extra year due to sports injury  

- **2012 – 2018**  
  **Niftarlake College, Maarssen, the Netherlands**  
  *General Secondary Education (upper-intermediate level)*  

## Work Experience {-}

- **Jul 2024 – Present**  
  **Cell and Gene Therapy Facility Intern, Prinses Maxima Centrum voor Kinderoncologie, Utrecht**  
  - Environmental monitoring and PQ of cleanroom under ISO and GMP guidelines.  

- **Oct 2023 – Present**  
  **Founder, Kokoro Skincare, Rotterdam**  
  - Founded Kokoro Skincare, managing strategy, compliance, and marketing.  
  - Expanded to Germany and Belgium, building a trusted Japanese beauty e-commerce brand.  

- **Dec 2023 – Present**  
  **Freelance Business Analyst, Remote**  
  - Streamlined reporting processes and translated data into user-friendly reports.  
  - Supported stakeholders in data-driven decision-making.  

- **Feb 2022 – Nov 2022**  
  **Laboratory Technician, Saltro BV, Utrecht**  
  - Executed precise analysis of COVID-19 samples using rt-qPCR techniques.  

- **Jul 2021 – Dec 2021**  
  **Laboratory Technician, Eurofins, Barneveld**  
  - Conducted soil and water pretreatment for ICP-MS analysis.  
  - Measured diverse environmental parameters.  

## Activities {-}

- **Sep 2023 – Present**  
  **Head of Partnership Committee, CSA-EUR, Rotterdam**  

- **Sep 2023 – Jun 2024**  
  **Active Member, Delft Committee, CSA-EUR, Rotterdam**  

- **Jan 2020 – Present**  
  **Sponsored Badminton Player, Victor Europe GmbH, Germany**  

## Additional Skills {-}

- **Languages**: English (Professional), Dutch (native)  
- **Software & Tools**:  
  - Microsoft Office (Outlook, Word, Excel, PowerPoint)  
  - Power BI (good command)  
  - IBM SPSS Statistics (fair command)  
  - RStudio (fair command)  
- **Driving License**: Full  
- **Hobbies**: Fitness, Badminton, Reading, Photography  


