# Reproducable research part 1

## Heterologous prime-boost immunisation with mRNA- and AdC68-based 2019-nCoV variant vaccines induces broad-spectrum immune responses in mice
Xingxing Li, Jingjing Liu, Wenjuan Li, Qinhua Peng, Miao Li, Zhifang Ying, Zelun Zhang, Xinyu Liu, Xiaohong Wu, Danhua Zhao, Lihong Yang, Shouchun Cao, Yanqiu Huang, Leitai Shi, Hongshan Xu, Yunpeng Wang, Guangzhi Yue, Yue Suo, Jianhui Nie, Weijin Huang, Jia Li, * and Yuhua Li.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10050358/ (add reference later)

### Study purpose
There was no concise statement in the introduction of the article, that established the reason the research was conducted.

### Study location
The study location has been mentioned in the methods, it was conducted at National institute for food and drug control (NIFDC).

### Ethics statement
There is a small ethics statement on handling of the animals and a small section on conflict of interest, this states there have been no conflicts with any other party.

### Funding statement
There is no section on fundings, however there is a section on acknowledgements. Here 2 companies are acknowledged for the provision of vaccines, it is rather unclear if these were provided for free or bought.

### Data availability statement and location
There is a small section where supplementary materials can be accessed. THere is a download link to the 'data sheet'. The sheet is a word doc with the processed data in figures in a doc file. Access to raw data would be better to have. It does however mention that you can inquire for more data but it requires you to contact the authors but, there is no author contact info available. Furthermore no code was used for this research.
