# Reproducable research part 1

## Heterologous prime-boost immunisation with mRNA- and AdC68-based 2019-nCoV variant vaccines induces broad-spectrum immune responses in mice
Xingxing Li, Jingjing Liu, Wenjuan Li, Qinhua Peng, Miao Li, Zhifang Ying, Zelun Zhang, Xinyu Liu, Xiaohong Wu, Danhua Zhao, Lihong Yang, Shouchun Cao, Yanqiu Huang, Leitai Shi, Hongshan Xu, Yunpeng Wang, Guangzhi Yue, Yue Suo, Jianhui Nie, Weijin Huang, Jia Li, * and Yuhua Li.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10050358/ (add reference later)

Add research question
Add summary methode en resultaten

#Reproducable research part 2

### Study purpose
There was no concise statement in the introduction of the article, that established the reason the research was conducted.

### Study location
The study location has been mentioned in the methods, it was conducted at National institute for food and drug control (NIFDC).

### Ethics statement
There is a small ethics statement on handling of the animals and a small section on conflict of interest, this states there have been no conflicts with any other party.

### Funding statement
There is no section on fundings, however there is a section on acknowledgements. Here 2 companies are acknowledged for the provision of vaccines, it is rather unclear if these were provided for free or bought.

### Data availability statement and location
There is a small section where supplementary materials can be accessed. THere is a download link to the 'data sheet'. The sheet is a word doc with the processed data in figures in a doc file. Access to raw data would be better to have. It does however mention that you can inquire for more data but it requires you to contact the authors but, there is no author contact info available. Furthermore no code was used for this research.

#Reproducable research b part 1

Since no code was used I decided to reproduce another article which was this the following:

## Estimating the effects of non-pharmaceutical interventions on COVID-19 in Europe
(https://www.nature.com/articles/s41586-020-2405-7)
The paper has  R code shared in the project environment and has clear instructions how to reproduce the data from the paper.
(Describe the code:)
The script runs smoohtly after installing all packages. I got the code from : https://github.com/ImperialCollegeLondon/covid19model.git

It clearly states version 7 was used for the Nature paper so I used that one. For this base-nature.r script was used.
On a scale from 1-5 I would rate this paper a 5 in how easy it was to reproduce. I could import the all the scripts from their github and rerun their data through the scripts the used.

```{r visualization, eval=FALSE, warning=FALSE}
library(rstan)
library(data.table)
library(lubridate)
library(gdata)
library(dplyr)
library(tidyr)
library(EnvStats)
library(optparse)
library(stringr)
library(bayesplot)
library(matrixStats)
library(scales)
library(gridExtra)
library(ggpubr)
library(cowplot)
library(ggplot2)
library(abind)

source('~/Portfolio-AlexS/Opdracht 4 - Reproducible Science/4b - Nature article files/scripts/process-covariates.r')

# Commandline options and parsing
parser <- OptionParser()
parser <- add_option(parser, c("-D", "--debug"), action="store_true",
                     help="Perform a debug run of the model")
parser <- add_option(parser, c("-F", "--full"), action="store_true",
                     help="Perform a full run of the model")
cmdoptions <- parse_args(parser, args = commandArgs(trailingOnly = TRUE), positional_arguments = TRUE)

# Default run parameters for the model
if(is.null(cmdoptions$options$debug)) {
  DEBUG = Sys.getenv("DEBUG") == "TRUE"
} else {
  DEBUG = cmdoptions$options$debug
}

# Sys.setenv(FULL = "TRUE")
if(is.null(cmdoptions$options$full)) {
  FULL = Sys.getenv("FULL") == "TRUE"
} else {
  FULL = cmdoptions$options$full
}

if(DEBUG && FULL) {
  stop("Setting both debug and full run modes at once is invalid")
}

if(length(cmdoptions$args) == 0) {
  StanModel = 'base-nature'
} else {
  StanModel = cmdoptions$args[1]
}

print(sprintf("Running %s",StanModel))
if(DEBUG) {
  print("Running in DEBUG mode")
} else if (FULL) {
  print("Running in FULL mode")
}

cat(sprintf("Running:\nStanModel = %s\nDebug: %s\n",
            StanModel,DEBUG))

# Read which countires to use
countries <- readRDS('~/Portfolio-AlexS/Opdracht 4 - Reproducible Science/4b - Nature article files/regions.rds')
# Read deaths data for regions
d <- readRDS('~/Portfolio-AlexS/Opdracht 4 - Reproducible Science/4b - Nature article files/COVID-19-up-to-date.rds')
# Read IFR and pop by country
ifr.by.country <- readRDS('~/Portfolio-AlexS/Opdracht 4 - Reproducible Science/4b - Nature article files/popt-ifr.rds')

# Read interventions
interventions <- readRDS('~/Portfolio-AlexS/Opdracht 4 - Reproducible Science/4b - Nature article files/interventions.rds')

forecast <- 0 # increase to get correct number of days to simulate
# Maximum number of days to simulate
N2 <- (max(d$DateRep) - min(d$DateRep) + 1 + forecast)[[1]]

processed_data <- process_covariates(countries = countries, interventions = interventions, 
                                     d = d , ifr.by.country = ifr.by.country, N2 = N2)

stan_data = processed_data$stan_data
dates = processed_data$dates
deaths_by_country = processed_data$deaths_by_country
reported_cases = processed_data$reported_cases
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
m = stan_model(paste0('~/Portfolio-AlexS/Opdracht 4 - Reproducible Science/4b - Nature article files/',StanModel,'.stan'))

if(DEBUG) {
  fit = sampling(m,data=stan_data,iter=40,warmup=20,chains=2)
} else if (FULL) {
  fit = sampling(m,data=stan_data,iter=1800,warmup=1000,chains=5,thin=1,control = list(adapt_delta = 0.99, max_treedepth = 20))
} else { 
  fit = sampling(m,data=stan_data,iter=600,warmup=300,chains=4,thin=1,control = list(adapt_delta = 0.95, max_treedepth = 10))
}   

out = rstan::extract(fit)
prediction = out$prediction
estimated.deaths = out$E_deaths
estimated.deaths.cf = out$E_deaths0

# Use fixed JOBID for reproducible filename (you can change '2048690' to any label you want)
JOBID <- "2048690"
print(sprintf("Jobid = %s",JOBID))

countries <- countries$Regions
save(fit,prediction,dates,reported_cases,deaths_by_country,countries,estimated.deaths,estimated.deaths.cf,stan_data, file=paste0('~/Portfolio-AlexS/Opdracht 4 - Reproducible Science/4b - Nature article files/Results/',StanModel,'-',JOBID,'-stanfit.Rdata'))


library(bayesplot)
filename <- paste0(StanModel,'-',JOBID)

print('Generating mu, rt plots')
mu = (as.matrix(out$mu))
colnames(mu) = countries
g = (mcmc_intervals(mu,prob = .9))
ggsave(sprintf("~/Portfolio-AlexS/Opdracht 4 - Reproducible Science/4b - Nature article files/%s-mu.png",filename),g,width=4,height=6)
tmp = lapply(1:length(countries), function(i) (out$Rt_adj[,stan_data$N[i],i]))
Rt_adj = do.call(cbind,tmp)
colnames(Rt_adj) = countries
g = (mcmc_intervals(Rt_adj,prob = .9))
ggsave(sprintf("~/Portfolio-AlexS/Opdracht 4 - Reproducible Science/4b - Nature article files/figures/%s-final-rt.png",filename),g,width=4,height=6)

print("Generate 3-panel plots")
source("~/Portfolio-AlexS/Opdracht 4 - Reproducible Science/4b - Nature article files/scripts/plot-3-panel.r")
make_three_panel_plot(filename)

print('Covars plots')
source('~/Portfolio-AlexS/Opdracht 4 - Reproducible Science/4b - Nature article files/scripts/covariate-size-effects.r')
plot_covars(filename)

print('Making table')
source('~/Portfolio-AlexS/Opdracht 4 - Reproducible Science/4b - Nature article files/scripts/make-table.r')
make_table(filename)

```

